First pass on Info
Readme-Workflows/readme-replacer pull request #3
Opened 2021-07-12 07:02 UTC by Andre601

## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [x] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

First pass on updating the README with valuable information.

Things left to do:
- [ ] Add Workflow structure

Closes #

[contributing]: CONTRIBUTING.md

2021-07-15 15:28 UTC, PuneetGopinath requested changes
Cool! But some small changes

2021-07-15 15:28 UTC, PuneetGopinath commented on README.md
> +You can find an [Example JSON file][example] with some recommended placeholders in this Repository.
```suggestion
You can find an [default JSON file][default] which will be the default placeholders in the workflow.
```

2021-07-15 15:28 UTC, PuneetGopinath commented on README.md
> +[example]: https://github.com/Readme-Workflows/readme-replacer/blob/main/src/replacers.json
```suggestion
[default]: https://github.com/Readme-Workflows/readme-replacer/blob/main/src/replacers.json
```

2021-07-15 16:05 UTC, PuneetGopinath requested changes
1 minor mistake

2021-07-15 16:05 UTC, PuneetGopinath commented on README.md
> +You can find a [JSON file][default] which would be the default placeholders in the workflow in this repository.
```suggestion
You can find a [JSON file][default] which would be the default placeholders in the workflow.
```
It's not in this repository, that is default for all users, wherever and whoever uses this action will use this as the default replacers

2021-07-15 16:06 UTC, PuneetGopinath commented on README.md
> +You can find a [JSON file][default] which would be the default placeholders in the workflow in this repository.
Yeah, I myself forgot to remove that. Didn't notice.

2021-07-15 16:09 UTC, Andre601 commented on README.md
> +You can find a [JSON file][default] which would be the default placeholders in the workflow in this repository.
It's still located within this repository so it's correct.

2021-07-15 16:12 UTC, PuneetGopinath commented on README.md
> +You can find a [JSON file][default] which would be the default placeholders in the workflow in this repository.
> It's still located within this repository so it's correct.

I don't know what to reply for this, let's wait for @abhijoshi2k

2021-07-15 16:15 UTC, Andre601 commented on README.md
> +You can find a [JSON file][default] which would be the default placeholders in the workflow in this repository.
Just read the message with your changes and tell me if it makes sense.
It say you can FIND a file... where? It wouldn't mention the location.

2021-07-15 16:29 UTC, abhijoshi2k reviewed
@Andre601 Can we provide an explanation on how this repository is linked with the `Readme-Icons` repository? The default replacers for readme icons will be added in #2 .

2021-07-15 19:25 UTC, Andre601 commented
> @Andre601 Can we provide an explanation on how this repository is linked with the `Readme-Icons` repository? The default replacers for readme icons will be added in #2 .

Not really sure it's worth to mention this...
At most maybe a "See also" section that just links to the other projects

2021-07-16 03:19 UTC, PuneetGopinath approved these changes

2021-07-16 06:05 UTC, abhijoshi2k approved these changes

2021-07-16 06:07 UTC, abhijoshi2k commented
@Andre601 Should we merge this? Or is there anything left to be added?
Asking because there's still `in progress` label here.

2021-07-16 06:09 UTC, PuneetGopinath commented
> @Andre601 Should we merge this? Or is there anything left to be added?
> Asking because there's still `in progress` label here.

I think there is, because Andre added `Add workflow structure` in the description.

2021-07-16 06:24 UTC, Andre601 commented
I forgot to update the description. It should now be ready, but I would request you to quickly check the workflow setup for if it would be the right syntax, or if it would require some changes.

2021-07-16 06:35 UTC, PuneetGopinath commented on README.md
> +    - cron: '*/30 * * * *' # Activate every 30 minutes
@abhijoshi2k Is this cron required, or should it trigger on push?

2021-07-16 06:43 UTC, abhijoshi2k commented on README.md
> +    - cron: '*/30 * * * *' # Activate every 30 minutes
It depends on how user uses it. Keep it cron for now. User can change according to needs

2021-07-16 06:44 UTC, PuneetGopinath approved these changes

2021-07-16 06:45 UTC, abhijoshi2k commented
```
env:
	GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
@Andre601 We might need token to commit in repo. Refer [this file](https://github.com/abhijoshi2k/abhijoshi2k/blob/master/.github/workflows/test-replacer.yml)

2021-07-16 06:45 UTC, PuneetGopinath commented
> I forgot to update the description. It should now be ready, but I would request you to quickly check the workflow setup for if it would be the right syntax, or if it would require some changes.

@abhijoshi2k Check the syntax yourself, and comment if OK.

2021-07-16 06:47 UTC, Andre601 commented
> ```
> env:
> 	GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> @Andre601 We might need token to commit in repo. Refer [this file](https://github.com/abhijoshi2k/abhijoshi2k/blob/master/.github/workflows/test-replacer.yml)

done

2021-07-16 06:47 UTC, merged